In [1]:
import numpy as np

In [4]:
# 1、创建一个长度为10的一维全为0的ndarray对象，然后让第5个元素等于1
n = np.zeros(10)
n[4] = 1
n

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [19]:
# 2、创建一个元素为从10到49的ndarray对象
n2=np.arange(10,50,1)
n2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [20]:
# 3、将第2题的所有元素位置反转
n3 = n2[::-1]
n3

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [30]:
# 4、使用np.random.random创建一个10*10的ndarray对象，并打印出最大最小元素
n4 = np.random.random(size=(10,10))
n4_max = np.max(n4)
n4_max

0.9693111247387226

In [31]:
n4_min = np.min(n4)
n4_min

0.016979840528144496

In [52]:
# 5、创建一个10*10的ndarray对象，且矩阵边界全为1，里面全为0
n5 = np.ones((10,10))
n5[1:9,1:9] = 0
n5

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [7]:
# 6、创建一个每一行都是从0到4的5*5矩阵
n6 = np.arange(0,5)
n6 = np.array([n6,n6,n6,n6,n6])
n6


array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [10]:
# 7、创建一个范围在(0,1)之间的长度为12的等差数列
n7 = np.linspace(start = 0,stop = 1,num = 12,endpoint=False) 
n7

array([0.        , 0.08333333, 0.16666667, 0.25      , 0.33333333,
       0.41666667, 0.5       , 0.58333333, 0.66666667, 0.75      ,
       0.83333333, 0.91666667])

In [11]:
# 8、创建一个长度为10的随机数组并排序
n8 = np.random.randint(0,100,size=10)
n8

array([37, 62, 90, 14, 93, 24, 65, 87, 54, 43])

In [25]:
# 9、创建一个长度为10的随机数组并将最大值替换为0
n8 = np.random.randint(0,100,size=10)
n8_max = np.argmax(n8)
n8[n8_max] = 0
n8[n8_max]

0

In [5]:
# 10、如何根据第3列来对一个5*5矩阵排序？
n10 = np.random.randint(0,100,size=(5,5))
n10

array([[84, 50, 13, 23, 55],
       [91, 84, 76, 99, 14],
       [47, 87, 80, 21,  1],
       [56, 97,  6, 16, 82],
       [50, 35,  9, 85, 76]])

In [8]:
n10[:,2].sort()
n10

array([[84, 50,  6, 23, 55],
       [91, 84,  9, 99, 14],
       [47, 87, 13, 21,  1],
       [56, 97, 76, 16, 82],
       [50, 35, 80, 85, 76]])

In [71]:
# 11、给定一个4维矩阵，如何得到最后两维的和？
n11 = np.random.randint(0,100,size=(3,3,3,3))
n11

array([[[[ 6, 57, 94],
         [58, 16, 81],
         [34, 25, 61]],

        [[61, 50, 52],
         [10, 11, 71],
         [12, 90, 52]],

        [[ 0, 25, 97],
         [97, 52,  2],
         [ 4, 99, 46]]],


       [[[ 6, 64, 17],
         [18, 53, 32],
         [75, 65, 50]],

        [[24, 54, 38],
         [90, 92, 88],
         [ 9, 27, 22]],

        [[15, 54, 67],
         [22, 96, 81],
         [36, 56, 50]]],


       [[[57, 58, 45],
         [39, 44, 33],
         [68, 75, 63]],

        [[51, 12, 75],
         [12, 96, 80],
         [68, 20, 17]],

        [[70, 86, 87],
         [86, 46, 91],
         [ 6,  0, 89]]]])

In [35]:
n11_max = np.sum(n9[-1,-1,-2:])
n11_max

338

In [85]:
# 12、给定数组[1, 2, 3, 4, 5]，如何得到在这个数组的每个元素之间插入3个0后的新数组？
n12 = np.array([1,2,3,4,5])
n12

array([1, 2, 3, 4, 5])

In [116]:
n12_zero = np.zeros((1,15),dtype=int)
n12_zero

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [118]:
n12_new = n12.reshape((5,1))
n12_new2 = n12_zero.reshape(5,3)
n12_new3 = np.concatenate((n12_new,n12_new2),axis = 1)
n12_new3 = np.hstack(n12_new3)
n12_end = n12_new3[:-3]
n12_end

array([1, 0, 0, 0, 2, 0, 0, 0, 3, 0, 0, 0, 4, 0, 0, 0, 5])

In [119]:
# 13、给定一个二维矩阵，如何交换其中两行的元素？
n13 = np.random.randint(0,100,size = (4,4))
n13

array([[40, 83, 50, 46],
       [72, 23, 27, 25],
       [65, 73, 68, 24],
       [91, 24, 61, 63]])

In [120]:
odd = n13[0::2].copy()
n13[0::2] = n13[1::2] 
n13[1::2] = odd
n13

array([[72, 23, 27, 25],
       [40, 83, 50, 46],
       [91, 24, 61, 63],
       [65, 73, 68, 24]])

In [59]:
# 14、创建一个100000长度的随机数组，使用两种方法对其求三次方，并比较所用时间
n14 = np.random.randint(0,10,size=10000)
n14

array([7, 6, 6, ..., 6, 4, 3])

In [61]:
# 更快
%timeit n14_3 = n14*n14*n14
n14_3

28.8 µs ± 1.91 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


array([343, 216, 216, ..., 216,  64,  27])

In [62]:
# 更慢
%timeit n14_3 = np.power(n14,3)
n14_3

39.1 µs ± 1.68 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


array([343, 216, 216, ..., 216,  64,  27])

In [63]:
# 15、创建一个5*3随机矩阵和一个3*2随机矩阵，求矩阵积
n15_1 = np.random.randint(0,10,size=(5,3))
n15_2 = np.random.randint(0,10,size=(3,2))
n15 = np.dot(n15_1,n15_2)
n15

array([[77, 35],
       [89, 26],
       [58, 33],
       [69, 24],
       [40,  4]])

In [67]:
# 16、矩阵的每一行的元素都减去该行的平均值
n16 = np.random.randint(0,10,size=(5,3))
n16

array([[3, 9, 8],
       [2, 8, 9],
       [2, 8, 9],
       [1, 4, 8],
       [6, 2, 2]])

In [68]:
n16_avr = np.mean(n16)
n16_avr

5.4

In [70]:
n16 = n16 - n16_avr
n16

array([[-2.4,  3.6,  2.6],
       [-3.4,  2.6,  3.6],
       [-3.4,  2.6,  3.6],
       [-4.4, -1.4,  2.6],
       [ 0.6, -3.4, -3.4]])

In [56]:
#17、打印出以下函数（要求使用np.zeros创建8*8的矩阵）：
# [[0 1 0 1 0 1 0 1]
#  [1 0 1 0 1 0 1 0]
#  [0 1 0 1 0 1 0 1]
#  [1 0 1 0 1 0 1 0]
#  [0 1 0 1 0 1 0 1]
#  [1 0 1 0 1 0 1 0]
#  [0 1 0 1 0 1 0 1]
#  [1 0 1 0 1 0 1 0]]
n17 = np.zeros((8,8))
n17[1:8:2,0:8:2]=1
n17[0:8:2,1:8:2]=1
n17

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

In [127]:
# 18、正则化一个5*5随机矩阵
# 正则的概念：假设a是矩阵中的一个元素，max/min分别是矩阵元素的最大最小值，则正则化后a = (a - min)/(max - min)
n18 = np.random.randint(1,10,size=(5,5))
n18

array([[1, 8, 6, 7, 1],
       [9, 9, 5, 3, 3],
       [7, 1, 1, 8, 7],
       [7, 2, 9, 3, 5],
       [9, 8, 6, 2, 3]])

In [131]:
n18_max = np.max(n18)
n18_min = np.min(n18)

In [135]:
def re(n):
    for i in range(5):
        for j in range(5):
            n[i,j] = (n[i,j] - n18_min)/(n18_max - n18_min)
    return n
display(re(n18))

array([[0, 0, 0, 0, 0],
       [1, 1, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [1, 0, 0, 0, 0]])

In [136]:
# 19、将一个一维数组转化为二进制表示矩阵。例如
# [1,2,3]
# 转化为
# [[0,0,1],
# [0,1,0],
# [0,1,1]]
n19 = np.arange(5)
n19

array([0, 1, 2, 3, 4])

In [ ]:
# 20、实现冒泡排序法