In [1]:
import tensorflow as tf

D:\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [2]:
a = tf.constant(2)
b = tf.constant(3)

In [10]:
# 启动
# 算法运算
with tf.Session() as sess:
    print(sess.run(a))
    print(sess.run(a+b))
    print(sess.run(a*2*b))

2
5
12


第一种方式,声明常量进行了算数运算
第二种方式,声明placeholder,占位符

In [14]:
a = tf.placeholder(tf.int32)
b = tf.placeholder(tf.int32)
c = tf.placeholder(tf.int32)

In [12]:
# tensorflow
# 定义操作,原理图中的加减操作
# 加
add = tf.add(a,b)
# 减
sub = tf.subtract(a,b)
# 乘
mul = tf.multiply(a,b)
# 除
div = tf.divide(a,b)

In [13]:
# 启动具体操作
with tf.Session() as sess:
    # 加
    print(sess.run(add,feed_dict={a:2,b:3}))
    # 减
    print(sess.run(mul,feed_dict={a:2,b:3}))
    # 乘
    print(sess.run(div,feed_dict={a:3,b:7}))
    # 除
    print(sess.run(sub,feed_dict={a:2,b:3}))

5
6
0.42857142857142855
-1


In [15]:
#  声明ndarray,list
matrix1 = tf.constant([[3.,3.]])
matrix2 = tf.constant([[2.],[2.]])

In [26]:
# 更复杂的矩阵
import numpy as np
a = np.array([1,2,3,4,5,6],dtype=float).reshape((1,6))
b = np.linspace(-np.pi,np.pi,6,dtype=float).reshape((6,1))

In [27]:
matrix3 = tf.constant(a)
matrix4 = tf.constant(b)

In [16]:
# 矩阵乘法   matmul
# S算数乘法  multiply
product = tf.matmul(matrix1,matrix2)
add = tf.add(matrix1,matrix2)

In [18]:
# 常规的乘法
mul = tf.multiply(matrix1,matrix2)

In [19]:
# 开启会话,执行运算
with tf.Session() as sess:
    print(sess.run(product))  #  [[12.]]
    print(sess.run(add))
    #  [[5. 5.]
    #  [5. 5.]]
    print(" ")
    print(sess.run(mul))
    # [[6. 6.]
    # [6. 6.]]

[[12.]]
[[5. 5.]
 [5. 5.]]
 
[[6. 6.]
 [6. 6.]]


In [28]:
product = tf.matmul(matrix3,matrix4)
add = tf.add(matrix3,matrix4)
# 常规的乘法
mul = tf.multiply(matrix3,matrix4)
# 开启会话,执行运算
with tf.Session() as sess:
    print(sess.run(product))  #  [[12.]]
    print(sess.run(add))
    #  [[5. 5.]
    #  [5. 5.]]
    print(" ")
    print(sess.run(mul))
    # [[6. 6.]
    # [6. 6.]]

[[21.99114858]]
[[-2.14159265 -1.14159265 -0.14159265  0.85840735  1.85840735  2.85840735]
 [-0.88495559  0.11504441  1.11504441  2.11504441  3.11504441  4.11504441]
 [ 0.37168147  1.37168147  2.37168147  3.37168147  4.37168147  5.37168147]
 [ 1.62831853  2.62831853  3.62831853  4.62831853  5.62831853  6.62831853]
 [ 2.88495559  3.88495559  4.88495559  5.88495559  6.88495559  7.88495559]
 [ 4.14159265  5.14159265  6.14159265  7.14159265  8.14159265  9.14159265]]
 
[[ -3.14159265  -6.28318531  -9.42477796 -12.56637061 -15.70796327
  -18.84955592]
 [ -1.88495559  -3.76991118  -5.65486678  -7.53982237  -9.42477796
  -11.30973355]
 [ -0.62831853  -1.25663706  -1.88495559  -2.51327412  -3.14159265
   -3.76991118]
 [  0.62831853   1.25663706   1.88495559   2.51327412   3.14159265
    3.76991118]
 [  1.88495559   3.76991118   5.65486678   7.53982237   9.42477796
   11.30973355]
 [  3.14159265   6.28318531   9.42477796  12.56637061  15.70796327
   18.84955592]]
